import type { ExperienceRuntime } from '../experience-config';

type Vertex={u:number;a:number;phase:number;band:number};
type Particle={u:number;v:number;life:number;speed:number;branch:number};

export function createExperience(host:HTMLElement):ExperienceRuntime{
 host.innerHTML=`<div class="lab" style="position:relative;width:100%;height:100%;overflow:hidden;background:#030508;color:#91afbf;font:7px ui-monospace,monospace;letter-spacing:.08em"><canvas style="position:absolute;inset:0;width:100%;height:100%"></canvas><div class="lab__hud" style="position:absolute;z-index:2;top:7px;left:8px;display:flex;gap:6px;padding:4px 6px;border:1px solid rgba(98,159,185,.28);background:rgba(3,9,15,.84)"><label>GLYPH MATERIAL <input class="glyphs" value=" .,:;irsXA253hMHGS#9B&@" maxlength="32"></label><label>MODE <select class="mode"><option value="singularity">SINGULARITY</option><option value="lattice">LATTICE</option><option value="turbine">TURBINE</option></select></label></div><div style="position:absolute;z-index:2;top:50%;left:8px;display:flex;flex-direction:column;gap:7px;transform:translateY(-50%)"><label>FIELD <input class="field" type="range" min="0" max="100" value="68"></label><label>FLOW <input class="flow" type="range" min="0" max="100" value="42"></label></div><div style="position:absolute;z-index:2;right:8px;top:50%;display:flex;flex-direction:column;gap:3px;transform:translateY(-50%)"><button class="pulse">PULSE</button><button class="seed">SEED</button><button class="pause">PAUSE</button></div><div style="position:absolute;z-index:2;right:8px;bottom:7px;left:8px;display:flex;justify-content:space-between"><span class="readout">GPU FIELD / 0.00ms</span><span>DRAG UI TO COMPOSE</span></div></div>`;
 const root=host.firstElementChild as HTMLElement,canvas=root.querySelector('canvas') as HTMLCanvasElement,ctx=canvas.getContext('2d')!;let w=1,h=1,d=1,t=0,last=0,raf=0,paused=false,field=.68,flow=.42,impulse=0,seed=1,mode='singularity',dead=false;
 const vertices:Vertex[]=[],particles:Particle[]=[];const state={cols:64,rows:34,points:720,particles:340};const glyphs=()=>((root.querySelector('.glyphs') as HTMLInputElement)?.value||'.#');const random=(n:number)=>{const v=Math.sin(n*91.17+seed*17.3)*43758.5453;return v-Math.floor(v)};
 function geometry(){vertices.length=0;for(let i=0;i<state.points;i++){const u=i/state.points;vertices.push({u,a:u*Math.PI*2,phase:random(i*2)*6.28,band:i%9})}}
 function makeParticles(){particles.length=0;for(let i=0;i<state.particles;i++)particles.push({u:random(i*2),v:random(i*4),life:random(i*7),speed:.1+random(i*9)*.4,branch:i%9})}
 function resize(){const b=root.getBoundingClientRect();w=Math.max(1,b.width);h=Math.max(1,b.height);d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}
 function point(v:Vertex,time:number){const a=v.a+time*(.18+flow*.22),u=v.u;if(mode==='lattice'){const r=.28+.11*Math.sin(a*8+time);return[Math.cos(a)*r,(u-.5)*1.15,Math.sin(a)*r]}if(mode==='turbine'){const r=.14+u*.62;return[Math.cos(a+u*4)*r,Math.sin(a*3+time)*.18+(u-.5)*1.1,Math.sin(a+u*4)*r]}const r=.22+u*.55+.09*Math.sin(a*3+time)+.04*Math.sin(a*11-u*18);return[Math.cos(a)*r,(u-.5)*1.12+.1*Math.sin(a*2-time),Math.sin(a)*r]}
 function project(p:number[],scale:number){const q=1/(1.55-p[2]*.55);return[w*.5+p[0]*scale*q,h*.5+p[1]*scale*q,q]}
 function draw(){const chars=glyphs(),cols=state.cols,rows=state.rows,cw=w/cols,ch=h/rows,scale=Math.min(w,h)*.34,buffer=new Float32Array(cols*rows);for(const v of vertices){const q=project(point(v,t),scale),x=Math.floor(q[0]/cw),y=Math.floor(q[1]/ch);if(x>=0&&x<cols&&y>=0&&y<rows){const i=y*cols+x;buffer[i]=Math.max(buffer[i],.25+q[2]*.5+field*.25)}}ctx.fillStyle='#030508';ctx.fillRect(0,0,w,h);ctx.font='9px monospace';ctx.textAlign='center';ctx.textBaseline='middle';for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const value=buffer[y*cols+x];if(value<=.04)continue;const i=Math.min(chars.length-1,Math.floor(Math.min(1,value)*chars.length));ctx.fillStyle=`rgba(120,${180+value*50},255,${.35+value*.55})`;ctx.fillText(chars[i]===' '?'·':chars[i],x*cw+cw/2,y*ch+ch/2)}for(const p of particles){if(!paused){p.life+=.01*p.speed*(1+flow);if(p.life>1){p.life=0;p.u=random(p.life+p.branch)}}const v={u:p.u+p.life*.22,a:(p.u+p.life*.22)*6.28,phase:0,band:p.branch},q=project(point(v,t),scale),dist=p.life*(.5+impulse);ctx.fillStyle=`rgba(74,205,255,${.08+(1-p.life)*.3})`;ctx.fillText(p.life<.15?'✦':chars[(p.branch+Math.floor(p.life*chars.length))%chars.length]||'·',q[0]+Math.cos(p.u*40)*dist*scale,q[1]+Math.sin(p.u*32)*dist*scale*.45)}impulse*=.94}
 function frame(ms:number){if(dead)return;const dt=Math.min(.05,(ms-last||16)/1000);last=ms;if(!paused)t+=dt;draw();const r=root.querySelector('.readout');if(r)r.textContent=`CANVAS / ${Math.round(dt*1000)}ms`;raf=requestAnimationFrame(frame)}
 const observer=new ResizeObserver(resize);const onMode=(e:Event)=>{mode=(e.target as HTMLSelectElement).value};const onPulse=()=>{impulse=1};const onSeed=()=>{seed++;geometry();makeParticles()};const onPause=(e:Event)=>{paused=!paused;(e.currentTarget as HTMLButtonElement).textContent=paused?'PLAY':'PAUSE'};const onField=(e:Event)=>field=+(e.target as HTMLInputElement).value/100;const onFlow=(e:Event)=>flow=+(e.target as HTMLInputElement).value/100;
 observer.observe(root);root.querySelector('.mode')?.addEventListener('change',onMode);root.querySelector('.pulse')?.addEventListener('click',onPulse);root.querySelector('.seed')?.addEventListener('click',onSeed);root.querySelector('.pause')?.addEventListener('click',onPause);root.querySelector('.field')?.addEventListener('input',onField);root.querySelector('.flow')?.addEventListener('input',onFlow);geometry();makeParticles();resize();last=performance.now();raf=requestAnimationFrame(frame);
 return{destroy(){if(dead)return;dead=true;cancelAnimationFrame(raf);observer.disconnect();root.querySelector('.mode')?.removeEventListener('change',onMode);root.querySelector('.pulse')?.removeEventListener('click',onPulse);root.querySelector('.seed')?.removeEventListener('click',onSeed);root.querySelector('.pause')?.removeEventListener('click',onPause);root.querySelector('.field')?.removeEventListener('input',onField);root.querySelector('.flow')?.removeEventListener('input',onFlow);host.replaceChildren()}};
}
