import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import type { ExperienceRuntime } from '../experience-config';

type Sparks={points:THREE.Points;positions:Float32Array;velocities:Float32Array;ages:Float32Array;lives:Float32Array;geometry:THREE.BufferGeometry;material:THREE.PointsMaterial;count:number};
type Bolt={group:THREE.Group;materials:THREE.Material[];light:THREE.PointLight;ground:THREE.Sprite;sparks:Sparks;start:THREE.Vector3;main:THREE.Vector3[];age:number;life:number;alive:boolean};

export function createExperience(host:HTMLElement):ExperienceRuntime{
 host.innerHTML='<div class="stage" style="position:relative;width:100%;height:100%;min-height:120px;overflow:hidden;background:#010108"><canvas style="position:absolute;inset:0;width:100%;height:100%;display:block;cursor:crosshair"></canvas></div>';
 const stage=host.firstElementChild as HTMLElement,canvas=stage.querySelector('canvas') as HTMLCanvasElement,scene=new THREE.Scene();scene.background=new THREE.Color(0x010108);scene.fog=new THREE.FogExp2(0x010108,.022);
 const camera=new THREE.PerspectiveCamera(38,1,.1,80);camera.position.set(2,4,11);const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.5;
 const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(1,1),2.2,.25,.03);composer.addPass(bloom);scene.add(new THREE.AmbientLight(0x080818,.04));
 const glow=(()=>{const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d')!,g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.08,'rgba(220,235,255,.8)');g.addColorStop(.2,'rgba(140,180,255,.3)');g.addColorStop(.4,'rgba(60,100,220,.08)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,128,128);return new THREE.CanvasTexture(c)})();
 const bolts:Bolt[]=[];let raf=0,clock=0,dead=false;let observer:ResizeObserver|null=null;
 function path(a:THREE.Vector3,b:THREE.Vector3,depth=6){const out:THREE.Vector3[]=[];function split(p:THREE.Vector3,q:THREE.Vector3,d:number){if(d>=depth){if(!out.length||out[out.length-1].distanceTo(p)>.001)out.push(p.clone());out.push(q.clone());return}const m=new THREE.Vector3().lerpVectors(p,q,.5),v=q.clone().sub(p),len=v.length();if(len<.01){out.push(p.clone(),q.clone());return}let n=new THREE.Vector3(-v.y,v.x,0);if(n.length()<.001)n.set(1,0,0);n.normalize();m.addScaledVector(n,(Math.random()-.5)*len*.38*(1-d/depth));split(p,m,d+1);split(m,q,d+1)}split(a,b,0);return out}
 function addLine(group:THREE.Group,materials:THREE.Material[],points:THREE.Vector3[],color:number,opacity:number){if(points.length<2)return;const material=new THREE.LineBasicMaterial({color,transparent:true,opacity});group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),material));materials.push(material)}
 function addSprites(group:THREE.Group,materials:THREE.Material[],points:THREE.Vector3[],color:number,size:number,opacity:number,mult=1){const step=Math.max(1,Math.floor(points.length/(points.length*mult)));for(let i=0;i<points.length;i+=step){const material=new THREE.SpriteMaterial({map:glow,color,transparent:true,opacity,blending:THREE.AdditiveBlending,depthWrite:false});const sprite=new THREE.Sprite(material);sprite.position.copy(points[i]);sprite.scale.set(size*(.6+Math.random()*.5),size*(.6+Math.random()*.5),1);group.add(sprite);materials.push(material)}}
 function make(x?:number,z?:number):Bolt{const sx=x??(Math.random()-.5)*9,sz=z??(Math.random()-.5)*7,start=new THREE.Vector3(sx,7.5+Math.random()*2,sz),end=new THREE.Vector3(sx+(Math.random()-.5)*1.5,-.45,sz+(Math.random()-.5)*1.5),main=path(start,end,7),group=new THREE.Group(),materials:THREE.Material[]=[];addLine(group,materials,main,0xffffff,1);addLine(group,materials,main,0x88ccff,.5);addLine(group,materials,main,0x4477dd,.2);addSprites(group,materials,main,0xaaccff,.35,.7);
  for(let i=0;i<2+Math.floor(Math.random()*2);i++){const off=.04+Math.random()*.1,a=start.clone().add(new THREE.Vector3((Math.random()-.5)*off,0,(Math.random()-.5)*off)),b=end.clone().add(new THREE.Vector3((Math.random()-.5)*off*2,(Math.random()-.5)*.05,(Math.random()-.5)*off*2)),branch=path(a,b,6);addLine(group,materials,branch,0x88bbff,.4);addLine(group,materials,branch,0x4488ff,.12);addSprites(group,materials,branch,0x88bbff,.15,.4,.5)}
  scene.add(group);const light=new THREE.PointLight(0x4488ff,0,28);light.position.copy(start);scene.add(light);const groundMat=new THREE.SpriteMaterial({map:glow,color:0x4488ff,transparent:true,opacity:.15,blending:THREE.AdditiveBlending,depthWrite:false}),ground=new THREE.Sprite(groundMat);ground.position.set(end.x,-.4,end.z);ground.scale.set(3,3,1);scene.add(ground);materials.push(groundMat);
  const count=150,positions=new Float32Array(count*3),velocities=new Float32Array(count*3),ages=new Float32Array(count),lives=new Float32Array(count);for(let i=0;i<count;i++){const p=main[Math.floor(Math.random()*main.length)];positions[i*3]=p.x+(Math.random()-.5)*.2;positions[i*3+1]=p.y+(Math.random()-.5)*.2;positions[i*3+2]=p.z+(Math.random()-.5)*.2;velocities[i*3]=(Math.random()-.5)*6;velocities[i*3+1]=Math.random()*5+1;velocities[i*3+2]=(Math.random()-.5)*6;lives[i]=.1+Math.random()*.5}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const material=new THREE.PointsMaterial({size:.06,transparent:true,opacity:1,blending:THREE.AdditiveBlending,depthWrite:false});const points=new THREE.Points(geometry,material);scene.add(points);return{group,materials,light,ground,sparks:{points,positions,velocities,ages,lives,geometry,material,count},start,main,age:0,life:.25+Math.random()*.35,alive:true}}
 function kill(b:Bolt){if(!b.alive)return;b.alive=false;scene.remove(b.group,b.light,b.ground,b.sparks.points);for(const m of b.materials)m.dispose();b.group.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose()});b.sparks.geometry.dispose();b.sparks.material.dispose()}
 function strike(x?:number,z?:number){while(bolts.length>4){const b=bolts.shift();if(b)kill(b)}const n=Math.random()<.5?2:1;for(let i=0;i<n;i++)bolts.push(make(x===undefined?undefined:x+(Math.random()-.5)*.5,z===undefined?undefined:z+(Math.random()-.5)*.5))}
 function resize(){const b=stage.getBoundingClientRect();if(!b.width||!b.height)return;camera.aspect=b.width/b.height;camera.updateProjectionMatrix();renderer.setSize(b.width,b.height);composer.setSize(b.width,b.height);bloom.setSize(b.width,b.height)}
 function frame(now:number){if(dead)return;const dt=Math.min(.05,(now-last)/1000||.016);last=now;clock+=dt;if(Math.random()<dt*.9)strike();for(let i=bolts.length-1;i>=0;i--){const b=bolts[i];b.age+=dt;const t=b.age/b.life;if(t>1){kill(b);bolts.splice(i,1);continue}const flick=.25+.75*(Math.sin(t*280+b.start.x*11)*.2+Math.sin(t*410+4.2)*.2+Math.sin(t*160+b.start.z*7+1.9)*.18+Math.sin(t*550+6.8)*.15+Math.random()*.15),op=Math.max(.02,Math.min(1,flick))*Math.min(1,t/.015)*Math.max(0,(1-t)/.1);for(const m of b.materials)m.opacity=op;b.light.intensity=op*25;b.ground.material.opacity=.15*op;b.ground.scale.setScalar(1+t*4);const s=b.sparks;for(let n=0;n<s.count;n++){s.ages[n]+=dt;if(s.ages[n]<s.lives[n]){s.positions[n*3]+=s.velocities[n*3]*dt;s.positions[n*3+1]+=s.velocities[n*3+1]*dt;s.positions[n*3+2]+=s.velocities[n*3+2]*dt;s.velocities[n*3]*=.93;s.velocities[n*3+1]-=3.5*dt;s.velocities[n*3+2]*=.93}else{s.positions[n*3]=b.start.x;s.positions[n*3+1]=-10;s.positions[n*3+2]=b.start.z}}s.geometry.attributes.position.needsUpdate=true;s.material.opacity=.9*op}camera.position.set(Math.sin(clock*.035)*12,4,Math.cos(clock*.035)*12);camera.lookAt(0,2.5,0);composer.render();raf=requestAnimationFrame(frame)}
 let last=performance.now();const onClick=(e:MouseEvent)=>{const b=canvas.getBoundingClientRect();strike((e.clientX-b.left)/b.width*18-9,(e.clientY-b.top)/b.height*(-13)+6.5)},onTouch=(e:TouchEvent)=>{e.preventDefault();const t=e.touches[0],b=canvas.getBoundingClientRect();strike((t.clientX-b.left)/b.width*18-9,(t.clientY-b.top)/b.height*(-13)+6.5)};
 observer=new ResizeObserver(resize);observer.observe(stage);canvas.addEventListener('click',onClick);canvas.addEventListener('touchstart',onTouch,{passive:false});resize();raf=requestAnimationFrame(frame);
 return{destroy(){if(dead)return;dead=true;cancelAnimationFrame(raf);observer?.disconnect();observer=null;canvas.removeEventListener('click',onClick);canvas.removeEventListener('touchstart',onTouch);for(const b of bolts)kill(b);composer.dispose();glow.dispose();renderer.forceContextLoss();renderer.dispose();host.replaceChildren()}};
}
